application: amherstcourses
version: 1
runtime: php
api_version: 1
threadsafe: false

handlers:
- url: /js
  static_dir: js
- url: /static
  static_dir: static
- url: /.*
  script: index.php
- url: /stylesheets
  static_dir: stylesheets/style.css